spring.application.name=YourCarYourWayPoc

# ===============================
# CONFIGURATION BASE DE DONNÉES
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/ycyw_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# CONFIGURATION JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false